

###
GET http://www.baidu.com
@Host=http://localhost:3000
###
GET {{Host}}/news
x-btcapi-usid: 05e4c12d-2182-4862-928a-a08cc79a5dec

###
GET http://omcenewssvcestg.chinacloudsites.cn/api/news
X-AppKey: 2014_MyBMW837
x-btcapi-usid: 05e4c12d-2182-4862-928a-a08cc79a5dec

###
GET {{Host}}/api/news?region=cn&locale=zh-cn&client=IOS&brand=1
x-usid: 05e4c12d-2182-4862-928a-a08cc79a5dec
AppVersion: 10.3.0

### ServiceManager
GET https://omcfeatabcedst.chinacloudsites.cn/api/servicemanager/v0/discoverallservices/v1?region=cn&locale=zh-cn&client=IOS&brand=1
AppVersion: 10.3.0
AppKey: 51dee986-d5b2-4af1-b129-4eaedc6c32b6